---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: renovate-operator-job
spec:
  dependsOn:
    - name: renovate-operator
  interval: 1h
  path: ./kubernetes/apps/renovate/renovate-operator/renovatejob
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: renovate
  wait: false
