---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:VBEj/3OjjbGAbOwCtsuwnzRO7tziwi2ApzfdpOFT5QCCJadgwve+56MLeP/7D6kfrA3Z+i8=,iv:rW1whf4euH351c7YfZW7ZPqfaBhKZV82a//7sUqk0CQ=,tag:4lkECKcSJ1j4Z9HoXoJarw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVGNzbFBDc2VMMjVVeExr
        bUwzV0htZ3VCUFdjMUFXSWVhWitWK1ppZVFrCi8vdURqTjRTMTlhSEtWRnp3WC85
        ZXcwZzJTWmdEZjRPQXp1QXlaOXhjWUEKLS0tIDdxa3hWd29CNDhaWXJkYnI0SGpD
        WTh5OTZsRVpjaWVKRjk0dzd1VyszQ00K0sDfr+3ZDXjpKDSEa1lTu0eLzhWhbRUi
        uNJxXqtsd8BXUVrQL8lWhH8cUr5yhGKUJESwLwwDFSqAsfdRAzA1xA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T14:30:20Z"
  mac: ENC[AES256_GCM,data:CYahV6gofQdECUl60eiyeAjnRhBR1DOCuQ8HD3chVVaHSDbZi77gXkQ/sow6bi3PviOCTyRfwD92seViTKOV0v6jNeFmnmD8oT3iLs4ybTkylokr4zq7wz521vom3o4rc1ZFxe0y4OcUXvG8o4DBHV+u5+0AmlZlBkoB1KB8FwY=,iv:3RoVySF514e0G5Wm3YNcMnd/cZyALlK1Z3SfIotKSOg=,tag:h/17b5gvRsgLqbCSjicpdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
