---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:/c/x/5PuwXKafVc=,iv:w57woz93iCqfdX4DyRx/l4bsiTo8Q/KSE0UuHHehogg=,tag:imXHHI1r7VkeDvzKF7hp0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOGhuK2QwR2pkbjVrOVdm
        SnBDUk9uQWUzZjEzRXZzL3dWZnc2ZkE5YVFZCnNxRGp3dUsxSHIxN2tJdDV3d1lU
        dVREcFVvbisxRk5pRDA5Zi82Sm5PMXMKLS0tIFNUUVdjZERZcDBzVXU5Q2VqbFFm
        OG9JV25BNmlqVjUrTTArYU9FN2dkS28Kxd8UpIBflM2jVvb01qXexMGNBjzjtUyM
        qCZ8TqRVz1Egs9Wx41leXoHOB22Rt2W8x84Sle8KJdSG1Hx6Vymynw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T14:30:20Z"
  mac: ENC[AES256_GCM,data:bZGPOGfgRE6XaDZcIvdnUaAMKNRjLE5lssVdoCiNU1wBdNgMjpgtDWLdh4CDLGsVT1zi9ftSfp0wYTOzGYR75EQuqIw6nrTMr1LOLtSpV/89HfmFIzYyB/++8kJkJxzPhgRbJM1sWchNladG+hGvij6mNnmSciMSCwXaNVxt2Zs=,iv:XdQc9o2BwRoGdRqq/y8LbW+tvxfRdjcwCmgo/huwpuk=,tag:tm3gwnT1mY2k08wYEBGgkQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
