---
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nT5qEHQ1ohiO2WbV8EKktltO17JePupLdHIOE9Q8QbM=,iv:JiqKK/s/l2aGWoEEinQJGh5y2NxCKQsgtGf5Q2nfJig=,tag:T2qAFx8NQ1fFlNiWJ08cfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtd2FwSGdFdE52RlR1Y0JQ
        TEJpRnVlQVhBVUtLNlpjTFpvdUhqZ3NrUWlVCnl6TmFSYTJ3ZnMrd2pPdWFNQ0tT
        OHFldDU2c1BSMzNyY1ZkbGtZUVNYMGMKLS0tIEo2WWlFdjUrYWc3NlNhQTlrc3lW
        a0NpNXNZcllEWHhYUDFTVFhkQVVNWEEKHBelLat+Ec29vgXmusGwaNYYt73NR7h6
        ImCUTQuuORuSQ45T8maxAomspXnaWrE+XMFp8CWPcwlcZg1I8iVi1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T14:30:20Z"
  mac: ENC[AES256_GCM,data:WCsnJqLerRcIr2f2UmMZP+vjRPM/KZfiLEE87WX4Jduqbee0rGDmvMGaxYlZCPYkd3YHrUBJfadiMwtxw5C3MA0uzxxOA8zmtKJC/A56WREc4u6pZQuZ9XMGrAz6ARFdUvoHaTvWSYpJFU9MYWcYQgm96svk9w1kIgcjGvJHQMg=,iv:U+S4iAPE+An0/fEd8QlKPFF5xRsyKB/9QoglVTzQUes=,tag:vXf/cvmljZyByuBrw9BCpg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
