---
apiVersion: v1
kind: Secret
metadata:
  name: kubeai-huggingface-secret
  namespace: kubeai
stringData:
  token: ENC[AES256_GCM,data:9/+VEfjL8qO0i4dRFkamj7QICVOVW/PQyItvbU5pWXbH08oXyQ==,iv:rrqLX/7Xhu92+GsXXIFu8ZaOrZ4Ztfwztz73AylVH/Y=,tag:maFIb3vOHJfK/BAdRHrj7Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZ0xCYm02SERvWDllTTkr
        eFNPSVZSZ3lEZDZpSWZCSksvSktkc1FFa1VrCkkveHNYc0haRUY0M05aWWY1cFF3
        b2hIdVJwemNFQlpHMHkrM3hJK0h3ZjQKLS0tIG1ISXZnTU9pa2VCaU9IL2d4SWJM
        ZitOd2JCNU82WjhkT09yRmtCajNMVGMKVCiTYPzGosCqAmK+2VsH9gZSlY+8s/gT
        P+pvSYiU2EMYL1QL+NETZDjnwIcZIMIOkULFxszobOgH2AClVmuHGA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-07T03:23:58Z"
  mac: ENC[AES256_GCM,data:cwn2zmhCYct/kgw8lw9kk29dE94ytP5D0E7xROyCLl6iA1EaWzQVPbfu0KMMns7r5pJdtOhTy5VH3FX3vMzZkHUdoBiZcQOauH6s8xNLdWzhzoN0VLbHA8QEToASMWw7cbPxSqUcFGkmrKlNwV4pxcIWCjPVNupEaJ9TUfsVT8A=,iv:tQPSECpLHqXATrptoNLiPENNk3JuE79iCURJBCOy35Y=,tag:3VDAvDs09nLz2l0DTvhU2g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
