---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: default
type: Opaque
stringData:
  SONARR__APP__APIKEY: ENC[AES256_GCM,data:GD8P7Q5FlvOwMGxBZBXS0yrPh+PkJ+pMvTss6eo90Uw=,iv:qsQQSDty0cP5Xx3dWOOxMmAnGA2rIZDf4zI9gP71LXQ=,tag:34Cso2YAXNqET+wX3l2uZQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:44:12Z"
  mac: ENC[AES256_GCM,data:aELLbN/XJSXrvOzvLWVcbnKwENV/Ma+NqKecOzn1c6fGhz6gJuUciSwfYsKabuzxJ4swnTBTag562WNXRSyR4UDwH4TbPqvhMvPdNACL0kRFup4TxeGgHlRx4oS6y82mpo5Cb8jw4PCx8jjatrgcC2se1KA/gAk3KjIReV33gnI=,iv:V/HBr6VwzDgwwRGVR/aEaadq7Vq7MC2v6Rc9OY/y/sg=,tag:p1/tPztntsZOm2f+QEx52g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: default
type: Opaque
stringData:
  RADARR__APP__APIKEY: ENC[AES256_GCM,data:7rBgpn4G/jI4Mzu17KtnZCkQ9jNoM1kNJnIeztfEFOc=,iv:zL4eMS0QMqeitZQ+AkOOeSF7pBBmMe9j5z1BgMmzTVk=,tag:Whh4SppsN/oGsC12cKvE0w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:44:12Z"
  mac: ENC[AES256_GCM,data:aELLbN/XJSXrvOzvLWVcbnKwENV/Ma+NqKecOzn1c6fGhz6gJuUciSwfYsKabuzxJ4swnTBTag562WNXRSyR4UDwH4TbPqvhMvPdNACL0kRFup4TxeGgHlRx4oS6y82mpo5Cb8jw4PCx8jjatrgcC2se1KA/gAk3KjIReV33gnI=,iv:V/HBr6VwzDgwwRGVR/aEaadq7Vq7MC2v6Rc9OY/y/sg=,tag:p1/tPztntsZOm2f+QEx52g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
  namespace: default
type: Opaque
stringData:
  SABNZBD__API__APIKEY: ENC[AES256_GCM,data:tfdNQYngNe6Xwf9MAbGwwP22FmkHbhc6st3EDa1oMN4=,iv:WUVebx5zXUGH6aXa9jeGIXlhe1Fzjzpiakg2yVApGhA=,tag:/Jq9WMv6vspvJ8tSpdWQgg==,type:str]
  SABNZBD__API__NZBKEY: ENC[AES256_GCM,data:+8dJVpqfqjrlpbLsxeY4tjsNtDnVj2iL2uZGhgf9uPQ=,iv:ARHmxaV2daTb9BRDylkvfrGgNgqRvxupZu1kdcH/IJo=,tag:iTmnJ8+XQLnU11yEc2ATSw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:44:12Z"
  mac: ENC[AES256_GCM,data:aELLbN/XJSXrvOzvLWVcbnKwENV/Ma+NqKecOzn1c6fGhz6gJuUciSwfYsKabuzxJ4swnTBTag562WNXRSyR4UDwH4TbPqvhMvPdNACL0kRFup4TxeGgHlRx4oS6y82mpo5Cb8jw4PCx8jjatrgcC2se1KA/gAk3KjIReV33gnI=,iv:V/HBr6VwzDgwwRGVR/aEaadq7Vq7MC2v6Rc9OY/y/sg=,tag:p1/tPztntsZOm2f+QEx52g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-secret
  namespace: default
type: Opaque
stringData:
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:4MRQKgjFsFGjTcBbfI73q+aX6Fb6CJjyUiP8mKjwGV8=,iv:3exol1oP4h0JLX5R+b4jVBKNn3CXWevm1To1qEL/4Ak=,tag:Ol/76luolGQkzSdNRzNDrQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:44:12Z"
  mac: ENC[AES256_GCM,data:aELLbN/XJSXrvOzvLWVcbnKwENV/Ma+NqKecOzn1c6fGhz6gJuUciSwfYsKabuzxJ4swnTBTag562WNXRSyR4UDwH4TbPqvhMvPdNACL0kRFup4TxeGgHlRx4oS6y82mpo5Cb8jw4PCx8jjatrgcC2se1KA/gAk3KjIReV33gnI=,iv:V/HBr6VwzDgwwRGVR/aEaadq7Vq7MC2v6Rc9OY/y/sg=,tag:p1/tPztntsZOm2f+QEx52g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
