---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: default
type: Opaque
stringData:
  SONARR__APP__APIKEY: ENC[AES256_GCM,data:Cb93kSt4auuxTmeA7uYwOxkXOXrxY+fvPkN14uU9u+E=,iv:nmNgyF08zjQArO6JNodRevhQZdvuHtA5b5Ukq5b1qlo=,tag:Nqs6nGaIMrxbXtNtsOI20w==,type:str]
  RADARR__APP__APIKEY: ENC[AES256_GCM,data:im6O14wzH9yWZqMoXXMkNpsYoZH5oQwyea5zmsrTqXA=,iv:vb31mJYJzNer9K+eAWkMZ3droIlApJbmU12Ktbd+BKI=,tag:JGOdZCgXuF8NxLIX37cKsQ==,type:str]
  SABNZBD__API__APIKEY: ENC[AES256_GCM,data:usmekC44sETTw+qEeAEIVnlneRlwn4sQjhuNhTXWe3g=,iv:xMlXJrWeSZW8Nsv0qSWuoRxtSWyyEboVheFlHzdst4E=,tag:/ZSviTo3GzykKgPw/bdNkg==,type:str]
  SABNZBD__API__NZBKEY: ENC[AES256_GCM,data:FSQhn64SAGlLmFG2y3MpipiamR+MvBGsnwfJBLLAVIU=,iv:OsgWPEnYtijX11g1pGaXzC848LoQBKdXk3hGhKyxcJc=,tag:JznUjHIz9GRcTVceJyDOFQ==,type:str]
  JELLYFIN_API_KEY: ENC[AES256_GCM,data:ElZ+pRnVBuiWAMbtBgfbdZ/5fztG1Afk7H+kkjZLfYE=,iv:S34Q1wcSo736xEqqKu91+/1TWTjCX5fqnRNTvEGfUhg=,tag:4Q6V0BA7cNsJfL7YbqljNw==,type:str]
  SEERR_API_KEY: ENC[AES256_GCM,data:K2XeReP4cSY=,iv:7IU/qZR8OLkQjHVn6rHm4stZq9F35Q+6mi4CQAiY2FU=,tag:frPLYlMsT+4SoaH1wdrAzw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOEd5cjYwTHlPb1NmVS9t
        cW5sSWkzVzJHN2RXN3JwQzc4RjJQaTRPNldzCmhmOTBTa2c3QktuUFd5SDZ6VjBT
        ZDV3ZS9KUWNFRGpOdVlEWklyMkZ2bG8KLS0tIDdBSk5CcEFKbjBmdjlxNHM2aWw5
        NTlGOE9ySmhzdXNuNVRqcVZkb0lDS2sK3daBKDbntPn9zRbX4AHZASLJr2gkFvZP
        YSPcq+si4rr8GAZsLPEzjvnYcyPn7ZbDzyIv610V7gayGrC4YYXw/w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T13:49:08Z"
  mac: ENC[AES256_GCM,data:fq/3CISCM86Yb1pwCrPHEnUyZDcVwaXMlLwWJoGOrRsktWCDUvc9VCJ452mG57hgfIOR5wd7VZLiQR1LtrWFrMUTJ8cicH1mcCYOI3akn9TTBUTNT+TfmeN+44fED1xQ4nx+eu74kMDr56zRAmFm42Su8bbT/+iZJg31zbsiyjQ=,iv:dqjGsol2sJ7Q3Mah8yc4iM2gW7C9+Vfe31gILJjd61w=,tag:/66ywOTF+6iifuD/F9yWwg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
