---
apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
  namespace: default
type: Opaque
stringData:
  SONARR__APP__APIKEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:32:07Z"
  mac: ENC[AES256_GCM,data:f3/HGMhE2E3Wgi7N//y8bdPjZYFixLo1SZ6OI/rQ74BqJEpte3keLi0noSnqOpKNog2f05xE7YwIEToaGPeJXxXdB+6rRESe4jHcEQvIjQpoBbUlcUpH2zxH8nIvgk85xX5hbjc1KlBPn4+BxsG/w+8LuOs8gV652plM1UXcQ98=,iv:7wRUMXvmlS/mRDc1ycCjXe90ly9gVMsaYFBozl8CzVw=,tag:oXHA47nR0wdu6wLv8C3Bdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
  namespace: default
type: Opaque
stringData:
  RADARR__APP__APIKEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:32:07Z"
  mac: ENC[AES256_GCM,data:f3/HGMhE2E3Wgi7N//y8bdPjZYFixLo1SZ6OI/rQ74BqJEpte3keLi0noSnqOpKNog2f05xE7YwIEToaGPeJXxXdB+6rRESe4jHcEQvIjQpoBbUlcUpH2zxH8nIvgk85xX5hbjc1KlBPn4+BxsG/w+8LuOs8gV652plM1UXcQ98=,iv:7wRUMXvmlS/mRDc1ycCjXe90ly9gVMsaYFBozl8CzVw=,tag:oXHA47nR0wdu6wLv8C3Bdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
  namespace: default
type: Opaque
stringData:
  SABNZBD__API__APIKEY: ""
  SABNZBD__API__NZBKEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:32:07Z"
  mac: ENC[AES256_GCM,data:f3/HGMhE2E3Wgi7N//y8bdPjZYFixLo1SZ6OI/rQ74BqJEpte3keLi0noSnqOpKNog2f05xE7YwIEToaGPeJXxXdB+6rRESe4jHcEQvIjQpoBbUlcUpH2zxH8nIvgk85xX5hbjc1KlBPn4+BxsG/w+8LuOs8gV652plM1UXcQ98=,iv:7wRUMXvmlS/mRDc1ycCjXe90ly9gVMsaYFBozl8CzVw=,tag:oXHA47nR0wdu6wLv8C3Bdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-secret
  namespace: default
type: Opaque
stringData:
  JELLYFIN_API_KEY: ""
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZzhRZDhpZk5qUURHTUxj
        SEw5YkgvY1JWT0xoOTQvUTIrM0NCVWl2R2dRCkZCM0ViWUVBVVJlZEdiWGR0aVhp
        WWlHMmhZQ1ZOWlpLU0poSkRhdDErZ0EKLS0tIDFmZ2gwY1NnRU1lZmxmRnlpTmhF
        TGdsYTJvOVBRVEpYUk9nMmJBQlBUbWsKWfCAhbFostpOchg92j8OyTaVmPwCjecA
        kpSKQQY4T/aodv1PgblXsKmh69UH3S3OlJwJttgdc41zjF4akTjNkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T01:32:07Z"
  mac: ENC[AES256_GCM,data:f3/HGMhE2E3Wgi7N//y8bdPjZYFixLo1SZ6OI/rQ74BqJEpte3keLi0noSnqOpKNog2f05xE7YwIEToaGPeJXxXdB+6rRESe4jHcEQvIjQpoBbUlcUpH2zxH8nIvgk85xX5hbjc1KlBPn4+BxsG/w+8LuOs8gV652plM1UXcQ98=,iv:7wRUMXvmlS/mRDc1ycCjXe90ly9gVMsaYFBozl8CzVw=,tag:oXHA47nR0wdu6wLv8C3Bdg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
