---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./app-secrets.sops.yaml
  - ./echo/ks.yaml
  - ./jellyfin/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./storage/ks.yaml
