---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: "external.${SECRET_DOMAIN}"
      recordType: CNAME
      targets:
        - "0d4a32ff-59cf-4a0a-9447-2f2f5d64e62f.cfargotunnel.com"
