---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:I6A5eM+VWilddW0InV2dff5DcH6wQ2Aec3eRZYVLXZXe1p5lbjt2L3mBbgzqhuRei6QKY1po6r0NHA6RMc/lIUkOtfQfvdaWrui7iL3z2joO4ZmZkYRqGcRcd7sGLLwR3Nz/i91VY35fXAuN6ocskp1NLWNsoUsD0W4VdMYIK+cIGd5AGkWoRlmebAxQvS3XmYdyyvGYUSGVIbtHw9oUWl1X3uz36CON3fsYDmCgEgPdN6pO,iv:lbruaZxmMefOk9nXQJa7Na7FddU+nzDrltYXwH0L6KA=,tag:NIltfffF/yJjb+M4M9m3IQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZM2doNXpVbXZ2MXVjNjRV
        Q0ZzdkEwYTJkSVJ5M1RTZVg2dTRBcDRsY3hVCkx6aG1uZjVzOWtvcXlvR3pUeVB0
        TGNycjVuT1hwNTNrcjhaUFh1NFd1dVUKLS0tIEhuRm9qejQ4Y1JJL1BqdHFCZmth
        eE5sbzUzQjVZcWpGR2pVbnRUUHgrRE0KBgteZ6G0N3Utr+zLiXhy9zh+/dpp/x35
        vMiV1QHGd+sKSem0aFUY9c12CZq59+BXt988m1MHGApHO0wWtnKzxA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T14:30:20Z"
  mac: ENC[AES256_GCM,data:12v2j2+F4kp5JJGpTyQiqp58OFHuJBEm071OJQj4g8raWoRWRzJublh8Y2WvlfdmVbQCtxnP9Y9hU9aVbt72R0BgnOWs29K85qI+WuYJOQQe73AvaH8xOl17/ZvUC+ZQqsIU+UWt/6BvLpyeJaYGYMIC71uXh0d8h2O4wpS4+g4=,iv:A4xn5BAKJUdXytDSvxXcenuMfswqHpPe0Mnk/SFXdGo=,tag:fwP9hiyWDltNu9n9brMsBQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
