---
apiVersion: v1
kind: Secret
metadata:
  name: smb-credentials
  namespace: kube-system
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:v5ve,iv:2TBvYtpPVy83Q4g7G1ElO/sVIPIcRyTaWHaAQ66d8lk=,tag:Un++uc827FP/YqgK2HFORQ==,type:str]
  password: ENC[AES256_GCM,data:CYVg1fztBPLExZi30Qxmf0thoULvqFCxpN+JdgRgSy0wNL0oadm+XIJ2ZCjU5r1iCHDeHfLzYMi/a2om0B6f5w==,iv:46p3HzrGtxeFwo7hdyAP0doskua7pOT6znKHMq1nFNU=,tag:NEC0n4RTCSEo40CJbFldTw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eTNqRW1EU3dGZ2JybDlw
        M1pFNGVDVmRUYW1KMVUrc3NEYk1lUjlMaTBZCmlVVlVQL2tqaVlWWllyaEswZEo1
        ZXkvLzl3WnNvQ0lkb2EwVG93Qy8wNFEKLS0tIC94anJieCtlN2hTVkUxZk5RV2R1
        Uk9yN1dzL29xeXB1SU81RFJhNTl4M1EKouWbrBMBAr2R5kD/BDLnwdOrE+YIZvbr
        N45n0AKUya6zQ37j+bws56X3OsmLWw9lJ3EqWIV5aYxqiZJXjfs1Hw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T19:56:44Z"
  mac: ENC[AES256_GCM,data:PtWfFJEwlc/jFh2ITjJWazDR/4RdovcYVuqHtiK3nYrC5xTReY4GDjLh4geAjYQzXiGMqqGlYkYR4ZbkL3yAC17Xv/8R877y7/R1Z75Gou3zkmGo9jJy3NHvB1GWdywebheC45DPjrZVJgVR0J4EhLcT3/l8/bjjrCvgIyc1JN0=,iv:ppCwu0AeFyVcdrwOxdtpzPPgItQp4+h4Xz+PLsKxs3g=,tag:x23e13URuTZ47pp/wanysQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
