---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-config
provisioner: smb.csi.k8s.io
parameters:
  source: //nas.winstead.io/Media
  subDir: config/${pvc.metadata.name}
  csi.storage.k8s.io/provisioner-secret-name: smb-credentials
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: smb-credentials
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0666
  - noperm
  - mfsymlinks
  - cache=strict
  - noserverino
  - nobrl
