---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: config
