---
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Tw6kVlV2kCdY2zRnHtrKUiPWPd2GQDK4tCKaaWj6egWHFo9sCl1/Zq4jZokMBqqYsxO4MMs=,iv:iAZlbcmwTEAs2pBhiCjW0Ar9VaOuF1+PlMenPEP9o3Q=,tag:DuyDXjdgsGPDw0tXX6wSJQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxdVNzdnFhSnVrUmV1QUtJ
        ekQzRjczYURUVW4vRjFPRmhTSTljd3JWMEJRCkd1c1J2a0VybzdBRTZseExTNlpu
        RTF3ZnAvSnY0RzFYcjNYWkVBSy9zYjQKLS0tIFc0Wnc3L0puNTA2R2drOHBtNHpt
        akVXNUFmVG5sMlNmeit5YlBDWE1iOTgKskF1M8uZ9FpZwSGNpSpq+i26dqHUv27Q
        tpi63V6kWYoir7O1nd7VyHTz3cfZnG8yrdcuI8tphTIXCwqA3l5Pwg==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T14:30:20Z"
  mac: ENC[AES256_GCM,data:gjNK2Y3GZYoM6PJ8VMfjpPbUmZpGM8VS+gxj1Juw4m/FezS6LP4PFRnVGOlrJgzOMO3YQcWnQ+AmVtqSFyoNLn+caVBd2kuEIYufOSdgHyM//ehqKHkAAa5XCvV3bzIq5chiibiW7aQ8gGRlrakB0DCqZucV4A2d6HZiXvqI31Q=,iv:17JCdHkVpq5+man/nQmoOoyqTWSfeyj8Wkr95FH1Lfw=,tag:vGEOHOR+CperGgUjEq3/QQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
