---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.20.0.2:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.20.0.2"
additionalMachineCertSans: *sans

clusterPodNets:
  - "10.42.0.0/16"
clusterSvcNets:
  - "10.43.0.0/16"

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-3"
    ipAddress: "10.20.0.102"
    installDisk: /dev/disk/by-id/nvme-Inland_NVMe_SSD_256GB_IBSCMC210625600183
    disks:
      - device: /dev/disk/by-id/nvme-INTEL_SSDPEKNW020T8_BTNH90810QKW2P0C
        partitions:
          - mountpoint: /var/lib/longhorn
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/e8df334dd37f5ff7d7bd95b0915b6e4b1f548d47a66b4b007a6997e268e17d56
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "58:47:ca:74:f6:90"
        dhcp: false
        addresses:
          - "10.20.0.102/16"
        routes:
          - gateway: "10.20.0.1"
            network: 0.0.0.0/0
        mtu: 1500
        vip:
          ip: "10.20.0.2"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"
  - "@./patches/global/machine-longhorn.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

