---
apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
  namespace: observability
type: Opaque
stringData:
  UNPOLLER_USER: ENC[AES256_GCM,data:dkltH3/zdFE=,iv:FuXB7fSjj1QlvYzL34T8u46b4g534ZloRD2ewv8Ok8s=,tag:GGa5XNRwNxxUuFMVOyGfpg==,type:str]
  UNPOLLER_PASS: ENC[AES256_GCM,data:2LXGkvIMcjzsRSfJ9U3AgzKh/4Q=,iv:04DHQ55GFbJAUKjm+No27h4odpPyWZNDE9LAZHKoUWs=,tag:kd4/JUSF7w45Lh3fyzJSzQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRjYyaGN2R3NHQlRnNDFr
        YW5BWU5uVnNpdG5PLzlTTTNVbW1yMXZkN240CjlERDE3eFFPaHFHL29HcGxGMXl2
        L0o0MGdaWU1pTDlHUFRpbWZRTG8yUW8KLS0tIHVVVjVGSUExNDVvOXl6bzBneU1i
        Ly9BckJaWUx6M1VkQ0p3RmtKS0hBU0EKCRBiyE2JIhg2K8JomPfvGj0TslGl1JyT
        vsCQA5hqyNjLRmVdje2oUNUDc8rbj//8sxHqOPtOPPOkgKDJh9vTmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T12:49:05Z"
  mac: ENC[AES256_GCM,data:zN/teUE11uzZEU8/o/Q+Keczfx+3ria128qPRTSHyo8TXmJ314F2iXMf1CSlGKzzjkUb2KulMh7702ci/k1blEBijzlJI/co9S8hgrvRzFSrIKSg6NC6nv1RHMndlw4IPx6SK+8A0CRVH6VegViWXbBRjCe6yfDGfCNY8E4nTLw=,iv:1pkRIEp1Lev0GD/Oh8Tp3BmTazlmGL/0qu3njSFC8ZQ=,tag:qqME8BkJsfJ0uvVz6Ysbgw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
