---
apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
  namespace: observability
type: Opaque
stringData:
  UNPOLLER_USER: ENC[AES256_GCM,data:dkltH3/zdFE=,iv:FuXB7fSjj1QlvYzL34T8u46b4g534ZloRD2ewv8Ok8s=,tag:GGa5XNRwNxxUuFMVOyGfpg==,type:str]
  UNPOLLER_PASS: ENC[AES256_GCM,data:paTTfk9lqts=,iv:erdODEHgHIs4PJ6NCmFTduhydAxVyLmwLBGl1WQqjyo=,tag:i4zwqgs2vyK7PRgkJ3QyQw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRjYyaGN2R3NHQlRnNDFr
        YW5BWU5uVnNpdG5PLzlTTTNVbW1yMXZkN240CjlERDE3eFFPaHFHL29HcGxGMXl2
        L0o0MGdaWU1pTDlHUFRpbWZRTG8yUW8KLS0tIHVVVjVGSUExNDVvOXl6bzBneU1i
        Ly9BckJaWUx6M1VkQ0p3RmtKS0hBU0EKCRBiyE2JIhg2K8JomPfvGj0TslGl1JyT
        vsCQA5hqyNjLRmVdje2oUNUDc8rbj//8sxHqOPtOPPOkgKDJh9vTmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T12:44:23Z"
  mac: ENC[AES256_GCM,data:sHMJXEG1R8haMPiFdUNEZs5oqgObun1qjVgvflHPXRazItJBoXKkEhGlOAMysk0ArjXY9x5XBgFGVq7hXvoi2aQNoI+HM3aENCETYpwTKdA8fOMTKh3RU6T74jLML/ii5NehfM9IeRT1oX6krufPCw5OFcPe3ffWbmv6/9Fv434=,iv:sqLhO9cx7rsWR2GVxk4GuuL2ZfC6oRWgs0xiiqmNsO0=,tag:omPLGQ+mNaKh7eenAg/vlg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
