apiVersion: v1
kind: Secret
metadata:
  name: qui-secret
  namespace: default
stringData:
  QUI__ADMIN_PASSWORD: ENC[AES256_GCM,data:hOC244+nx3OsJWL5tf2U1agYo3s88aNLVXO1Jiz9CSE=,iv:Wc3MGE/xf4LaMuOKoLAdprS1ajLA9hislmbGToF44kU=,tag:W4+f/tRlY2YW5Hf7dF/UKA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSytRNTlRWEdJZXFjY0Rw
        UGY4dm14WUtoVTd4NVBETGZ4RGhBZWdxNVNjCmxVYUx1ZmVMYVBLOHNTVTRQS0dk
        bEgwbG9MRmM1cUQwOGZkV1k3TFZTYncKLS0tIDhaaS8zbnhLbFZoYUJjTEtGMnEx
        alpZZmNTZ0dmY2ZLVmhxTzlsMGhDcmcKCuFK+dGo9AIMOollvEFAQcX+IzQsPPdT
        WOQirEsE3R4WIEIPOIXgpZvYw9purkOZujpc7HJWofJB0ABCoohA8g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-22T01:28:59Z"
  mac: ENC[AES256_GCM,data:ZWfhxV9EYZi6pTkL1guwBm+aweXFBjbh80gdvilcA+efDxtUWl05RouGvQa5KPsq8AX1DR7uyzB6wPykB0LH75aoENr1y5TIwNJvQSZfKrtc9wQlj8XdOKWgarHzSSqOhBIQCSN9GGQ/6GbVbW+GbmmOg4utDb5mkVuNX1A+GrU=,iv:E5yB77mtELwdw8VrbOaKm1frwCMSSun4q5v+5/vI37E=,tag:PRI+/mVqTPBDdGMHoG31/A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
