---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0666
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
    - nobrl
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: nas-media
    volumeAttributes:
      source: //nas.winstead.io/Media
    nodeStageSecretRef:
      name: smb-credentials
      namespace: kube-system
