---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: smb
  volumeName: media
