---
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secrets
stringData:
  #ENC[AES256_GCM,data:lI/97a+EaxH9nKSBBLS5K65BmJLDETUebhcpLqbTNA==,iv:nWF404ak7XL9ShC/dA/JXMr3+q62L4AWy3woX4SmDyI=,tag:+YrSISNEY002vqp61rSkmA==,type:comment]
  ANTHROPIC_API_KEY: ENC[AES256_GCM,data:Im4ybK7D1AiVkbSxwy4=,iv:8OYkF/nPZK8gPmUk5RSaJPm3vpMRlFSeMX3L9O59yhw=,tag:6rgpHEyAqcJaRezmBQFIGQ==,type:str]
  #ENC[AES256_GCM,data:fihY1yom8kN646SdNyVBmgD0kSOI,iv:VouAne6Rewv7YeCV47ugqTYVBadpNY0zX8iGVV0q1g8=,tag:2h0kE8BDAPp72L56a2sDOg==,type:comment]
  GITHUB_TOKEN: ENC[AES256_GCM,data:xwYiM9Vl8MRAr8Y=,iv:siYQ9O44kcBTsFNoUu3UAp91dnGuKDjBV9zqOlgWZlo=,tag:T8oLBHma4ExYPvF1BwpOUw==,type:str]
  #ENC[AES256_GCM,data:1UMG3HlJnt2g196t4kBip7gjxZpP9QLObRoCE+qyipMjlo5KPyaN,iv:hcKdBlpAH769D91Uy6ckvUVWQX0khxe2VyMe77ILYEo=,tag:atzb1FzpZ5vMxj3DnBTi+Q==,type:comment]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:qABZPUjTYA==,iv:4L2uFeNf707ONTy0rZdT0KlUQN5iPEsOM5IYKafeB/M=,tag:bT6MGf9psvGGsUnqZPJhuQ==,type:str]
  DISCORD_USER_ID: ENC[AES256_GCM,data:yDJGQnnDLQ==,iv:KpaedsX6DAo2aQZp5PWuTeoC9c/xJ/JGJYcOjFexyyc=,tag:KPniGS0kUgQ6FGSu+jBgUg==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:CqBCvjTInA==,iv:6/0JlL4NSu9AWCgzwXW+RQfR0kXf++qWGfRpm605d2Y=,tag:Bqkgh5oCVsPIBhVW8kcwxQ==,type:str]
  #ENC[AES256_GCM,data:wPfqoutRxhogJ4rdrw==,iv:7hjYX8xSM3q4uTjPeA9tInv9sdBxOxUTMjQ/URU2+rA=,tag:0bcvlZars5HZ799sh7Nqug==,type:comment]
  OPENCLAW_HOOK_TOKEN: ENC[AES256_GCM,data:NL0eYMBjeGUkSpxlzft/HNsW,iv:foKbD/3CY21sHh0g8M5DAIldbNgXQXEopS1kYerpRl0=,tag:zeDtzLCIOA0OJMEehf+L8A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWi94NWI3NDQ1c1JHOXFk
        czJuSU1QUHBwSnVCR2hnOTFYVWJnaVN0TWhJClJUWmU3aFMzTFZFbVQzQzBxenBQ
        dG9hc0ZydVRRWjJ2a0MvS1JJSytkRHMKLS0tIFFBd1QzZ1JLMmRkY093dlBYdWVj
        YndWUTMwU2RpQkNZYmtneThncTVXYnMK62ukPX670gj+F8brGuhdQdR8lhdSyYPE
        kWV3JpNzUHGYmQ/7SZxAwoqRUPY9X98plEA3uEo6tAhQ5sECzGrjmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T16:06:19Z"
  mac: ENC[AES256_GCM,data:AxxOqFoyMgovjgnO5LBLw1LBXmIrk6Qfo6msmGDZHjKxMGtvxq6WyuWodvqDlEh1SKVbWYaj/cxjum1XVTzgFjjZnaJzVcMf/wj4b2m647pJHc3NElaPQmyaerS3XTOWNjL/HwjKW185Sx8GvrjkOC9NtQJxQ5e0LRB9rehKkls=,iv:B4JXa6ti+67hs+WVvJkzie2DJso17Wf3/v2Pk1IogWY=,tag:ciIBaayEm6BQyJfCXNvToA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
