---
apiVersion: v1
kind: Secret
metadata:
  name: openclaw-secrets
stringData:
  OPENAI_API_KEY: ENC[AES256_GCM,data:cFd5vTiixE/IBYzkiHSZYAO3OVgnToX0TB+LiLFdakqOEBmnTGBXArctbgEr5nwjzITTTEfmtUdq/NDTP4SqEdFjq/+joGyS/9X5fSdqqVaizJjW7cUMdpS0Yh5RTZZwFr4t83g8VOgfkl8QLkvS7wA6tFg5cos31PsdkWRyYsafsvYSBgGGQfRgC2CUS2OaKpSKs2xXGqQxuzPNdmvXPH1bbts=,iv:YjhF5+iYGQ9H9FhtMZkAyL99Eq3q8BGSphL9+K77V+Q=,tag:iW/WMX3nd9pdgSynvK6Rvw==,type:str]
  GITHUB_TOKEN: ENC[AES256_GCM,data:mapz4uayfOdUlibncMX+ZGdtG38VE25RAHc4dYoBea0r+YW5kUxUeLAqDljYnDoKha3PO1oFjHOK8rX9OtUo9QEo3RW+d0Rs4/tVpH1qjJLW8RBxBCyUsq6q8vqV,iv:/QaAS1BZhWbt5pWdp5vYmkWWhpVXiYAer7yNyK46N/k=,tag:oWZdV+6nn5mqOgkw554xsQ==,type:str]
  DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:CcKkkT4StaLwqiFfwVHTYXzc0MtcI6OoGdb1lbaALYXqDs860aTokS3iSZSM+G/C6wjKhiwzpKRIcwDsd/PgcJVDwg89nGsy,iv:+GzZPEBEOY4oFQVFgnhJgcmc9GjjIAJAwSyupcWcCI4=,tag:C00+D9cbJMAsbc1uLelW2g==,type:str]
  DISCORD_USER_ID: ENC[AES256_GCM,data:7DhWf8JyTKT80IvuAyfj8QjGjUY=,iv:OeYOV0T7LQmrDxAON9iEPDCuaPP9IRdGYUIq3J9EUBw=,tag:HYrm+9n4QK8JdmxiKA7Zqw==,type:str]
  DISCORD_GUILD_ID: ENC[AES256_GCM,data:JaspupLNiFR28jU4w7MZa88diQ==,iv:Hl9N3RQdKJ5iTYfm4344XzumkzU9kWHphJ5e/QzirYI=,tag:l0AEzrsbW7YVp/D4uYRROg==,type:str]
  OPENCLAW_HOOK_TOKEN: ENC[AES256_GCM,data:wM0WyX7Jh9i17vsrsFa6Wgm+8t6U8lBfP2gBIl/zFAt0PDEq9IcUeXGNP7D91t8mp61xixHWFUrvX773VwDjeQ==,iv:wZTVSNOaVgXOW5gq7TYxmChXrnbs7qc459lYIK/WP2M=,tag:nVi3ULUIM+yj/3FKz6B0ig==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWi94NWI3NDQ1c1JHOXFk
        czJuSU1QUHBwSnVCR2hnOTFYVWJnaVN0TWhJClJUWmU3aFMzTFZFbVQzQzBxenBQ
        dG9hc0ZydVRRWjJ2a0MvS1JJSytkRHMKLS0tIFFBd1QzZ1JLMmRkY093dlBYdWVj
        YndWUTMwU2RpQkNZYmtneThncTVXYnMK62ukPX670gj+F8brGuhdQdR8lhdSyYPE
        kWV3JpNzUHGYmQ/7SZxAwoqRUPY9X98plEA3uEo6tAhQ5sECzGrjmQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1ahehja44hsq4vs6hzgne587xvl20v6utvvjkwefmzcy2p4srjf4sd6e8el
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-06T19:03:25Z"
  mac: ENC[AES256_GCM,data:3ggJBgK7JY+FBy8zFES1NFmGkLkMdgdbzmvNJdPleVcvZen2tWPtVL5mw1wxy0vQb4RwuXwjNEq8oJRlv0HA1qcdfIYP4sLF1a9ucAW971un4xd9CaTq3fwxGx9hUg3ZiFTy9xF4K8dCJVb8UZSQgTTmDt5ONdeji8f4P9X+vYA=,iv:cFANNjK8/bcRU3ZTWYhe3sy9LuzlhT4Z00FjUuidl9A=,tag:XbFwlTqLqs0pSNjOflwlew==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
