---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  interval: 1h
  values:
    controllers:
      recyclarr:
        type: cronjob
        cronjob:
          schedule: "0 3 * * *"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.6.0
            args:
              - "sync"
            envFrom:
              - secretRef:
                  name: app-secrets
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    persistence:
      config:
        type: configMap
        name: recyclarr-config
        globalMounts:
          - path: /config/recyclarr.yml
            subPath: recyclarr.yml
            readOnly: true
