---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true
  settings.yaml: |
    title: Home
    color: slate
    headerStyle: clean
    layout:
      Media:
        style: row
        columns: 4
      Downloads:
        style: row
        columns: 2
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: cluster
        nodes:
          show: false
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23
  services.yaml: |
    []
  bookmarks.yaml: |-
    []
  docker.yaml: ""
  proxmox.yaml: ""
  custom.css: ""
  custom.js: ""
