---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  chartRef:
    kind: OCIRepository
    name: homepage
  interval: 1h
  values:
    controllers:
      homepage:
        annotations:
          reloader.stakater.com/auto: "true"
        serviceAccount:
          name: homepage
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.13.1
            env:
              HOMEPAGE_ALLOWED_HOSTS: "homepage.${SECRET_DOMAIN}"
              TZ: America/New_York
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: &port 3000
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 512Mi
    defaultPodOptions:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    service:
      app:
        ports:
          http:
            port: *port
    route:
      app:
        hostnames:
          - "homepage.${SECRET_DOMAIN}"
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - path: /app/config/kubernetes.yaml
            subPath: kubernetes.yaml
            readOnly: true
          - path: /app/config/settings.yaml
            subPath: settings.yaml
            readOnly: true
          - path: /app/config/widgets.yaml
            subPath: widgets.yaml
            readOnly: true
          - path: /app/config/services.yaml
            subPath: services.yaml
            readOnly: true
          - path: /app/config/bookmarks.yaml
            subPath: bookmarks.yaml
            readOnly: true
          - path: /app/config/docker.yaml
            subPath: docker.yaml
            readOnly: true
          - path: /app/config/proxmox.yaml
            subPath: proxmox.yaml
            readOnly: true
          - path: /app/config/custom.css
            subPath: custom.css
            readOnly: true
          - path: /app/config/custom.js
            subPath: custom.js
            readOnly: true
      logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      nextjs-cache:
        type: emptyDir
        globalMounts:
          - path: /app/.next/cache
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
